### ISSUE TITLE
Natural agent not recognizing message sender correctly sometimes

### ISSUE THREAD

**Issue by rmed** [voiser/zoe-startup-kit#9]
This is very rare and has only happened a couple of times, but the natural or relay agents are not obtaining the user correctly from a jabber conversation. For instance, suppose the following `etc/zoe-users.conf` file:

```
[subject admin]
name = Rafa
twitter = a twitter
preferred = mail
jabber = a jabber address
mail = a mail
alias = rafa

[group admins]
members = admin

[group broadcast]
members = admin
```

Technically, my user is identified as `admin`, but for some reason Zoe gets the **alias** rather than the **subject** from time to time. Given that the agent manager checks this list for permissions, I want to find out if it is due to my way of handling the sender of the message or some confusion when fetching the users.

**Comment by voiser** [comment]
In this example, Zoe does not create one user but two: "admin" and "rafa":
```
$ ZOE_HOME=`pwd` PYTHONPATH=lib/python:lib/python-dependencies python3
Python 3.2.3 (default, Feb 20 2013, 20:08:02)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pprint
>>> import zoe
>>> subjects = zoe.Users().subjects()
>>> pprint.PrettyPrinter().pprint(subjects)
{'admin': {'alias': 'rafa',
           'id': 'admin',
           'jabber': 'a jabber address',
           'mail': 'a mail',
           'name': 'Rafa',
           'preferred': 'mail',
           'twitter': 'a twitter',
           'uniqueid': 'admin'},
 'rafa': {'alias': 'rafa',
          'id': 'rafa',
          'jabber': 'a jabber address',
          'mail': 'a mail',
          'name': 'Rafa',
          'preferred': 'mail',
          'twitter': 'a twitter',
          'uniqueid': 'admin'}}
```
Both users contain the same information, so if you only need to check for an email addres or so, you don't have to worry about it.

Notice that there is an extra entry in each user, "uniqueid", which points to the real ID of the user:

```
>>> subjects["admin"]["uniqueid"]
'admin'
>>> subjects["rafa"]["uniqueid"]
'admin'
```

If you are receiving a message via the relay agent, or you are writing a natural language command, you should receive this information automatically. As an example:

https://github.com/voiser/zoe-startup-kit/blob/master/agents/jabber/jabber.py#L91
https://github.com/voiser/zoe-startup-kit/blob/master/cmdproc/state_commands.pl#L42

(btw I am thinking that the email agent seems not to take this unique ID into account... I'll take a look)

Hope this helps.

**Comment by rmed** [comment]
Then, this means that what I need is the `"msg-sender-uniqueid=s" => \$sender,` part in the natural language command, as I'm checking the sender against the list of members of the `admins` group before performing actions in the agent manager. I'll add it when I get some time, although it will stop working with older versions of Zoe that do not have the unique id.
